[package]
name = "service_conventions"
version = "0.0.9"
edition = "2021"
description = "Conventions for services"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.22.0", features = [], optional = true }
opentelemetry-otlp = { version = "0.15.0", features = ["trace", "grpc-tonic", "http-proto", "reqwest-rustls", "tls"], optional = true }
opentelemetry-semantic-conventions = { version = "0.14.0", optional = true}
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"], optional = true }

tracing-subscriber = { version = "0.3.18", features = ["fmt", "json", "env-filter", "std", "registry"], optional = true }
tracing = { version = "0.1.40", optional = true}
tracing-opentelemetry = { version = "0.23.0", optional = true}

anyhow = {version = "1", optional = true}
once_cell = { version = "1.19.0", optional = true}
openidconnect = {version = "3.5.0", optional = true, features = ["accept-rfc3339-timestamps"]}
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = {version = "1.0", optional = true}
maud = { version="0.26.0", features = ["axum"], optional = true }
axum = { version = "0.7.5", optional = true}
tower-cookies = { version = "0.10.0", features = ["signed", "private", "axum-core"], optional = true}

url = { version = "2.5.0", optional = true }
email_address = {version = "0.2.4", optional = true}
http = {version = "1.1.0", optional = true}
axum-core =   {version = "0.4", optional = true}
async-trait = {version = "0.1", optional = true}

[features]
all = ["tracing", "oidc"]
default = ["tracing", "oidc"]
tracing = ["dep:opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry-semantic-conventions", "dep:tracing-subscriber", "dep:tracing", "dep:tracing-opentelemetry", "dep:opentelemetry_sdk"]
oidc = ["dep:anyhow", "dep:once_cell", "dep:openidconnect", "dep:serde", "dep:serde_json", "dep:maud", "dep:axum", "dep:tower-cookies", "dep:url", "dep:email_address", "dep:http", "dep:async-trait", "dep:axum-core"]

