[package]
name = "service_conventions"
version = "0.0.1"
edition = "2021"
description = "Conventions for services"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.22.0", features = [], optional = true }
opentelemetry-otlp = { version = "0.15.0", features = ["grpc-tonic", "http-proto"], optional = true }
opentelemetry-semantic-conventions = { version = "0.14.0", optional = true}
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"], optional = true }

tracing-subscriber = { version = "0.3.18", features = ["fmt", "json", "env-filter", "std", "registry"], optional = true }
tracing = { version = "0.1.40", optional = true}
tracing-opentelemetry = { version = "0.23.0", optional = true}

once_cell = { version = "1.19.0", optional = true}
openidconnect = {version = "3.4.0", optional = true}
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = {version = "1.0", optional = true}
maud = { version="0.26.0", features = ["axum"], optional = true }
axum = { version = "0.7.4", optional = true}
tower-cookies = { version = "0.10.0", features = ["signed", "private"], optional = true}

[features]
default = ["tracing"]
tracing = ["dep:opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry-semantic-conventions", "dep:tracing-subscriber", "dep:tracing", "dep:tracing-opentelemetry", "dep:opentelemetry_sdk"]
oidc = ["dep:once_cell", "dep:openidconnect", "dep:serde", "dep:serde_json", "dep:maud", "dep:axum", "dep:tower-cookies"]
