[package]
name = "service_conventions"
version = "0.0.1"
edition = "2021"
description = "Conventions for services"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.21.0", features = [], optional = true }
opentelemetry-otlp = { version = "0.14.0", features = ["grpc-tonic", "http-proto"], optional = true }
opentelemetry-semantic-conventions = { version = "0.13.0", optional = true}
opentelemetry_sdk = { version = "0.21.1", features = ["rt-tokio"], optional = true }

tracing-subscriber = { version = "0.3.18", features = ["fmt", "json", "env-filter", "std", "registry"], optional = true }
tracing = { version = "0.1.40", optional = true}
tracing-opentelemetry = { version = "0.22.0", optional = true}

[features]
default = ["tracing"]
tracing = ["dep:opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry-semantic-conventions", "dep:tracing-subscriber", "dep:tracing", "dep:tracing-opentelemetry", "dep:opentelemetry_sdk"]
