name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"

  rust_release:
    uses: "philipcristiano/workflows/.github/workflows/rust_release.yml@main"
    needs: [flake, rust]
    secrets:
      WF_GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      script: |
        cargo build
